title: MCR
author: a.moron

url: https://moronbandin.github.io/mcr/ 
description: > 
 notas del m√°ster de ciencias de las religiones de la upo/uc3m/ull
 
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

header_pages:
  - americanas/index.md
  - biblia/index.md
  - cristianismo/index.md
  - intro/index.md
  - islam/index.md
  - judaismo/index.md
  - lecturas/index.md  
  - orientales/index.md
  - politeismo/index.md
  - teoria/index.md
  - poder/index.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:  
  date_format: "%d %b, %Y"

social_links:
  - { platform: github,         user_url: "https://github.com/moronbandin" }
  - { platform: instagram,      user_url: "https://www.instagram.com/morounsito" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/amoron/" }
  - { platform: twitter,        user_url: "https://twitter.com/moronbandin" }

show_excerpts: true