title: MCR
author: a.moron
url: https://dh4ih.github.io/mcr1/ # root address of the site
description: > # description of the site (multiple lines allowed)
 Notes from MCR!
 
theme: minima

header_pages:
  - cristianismo: https://dh4ih.github.io/mcr1/cristianismo/
  - juda√≠smo: https://dh4ih.github.io/mcr1/judaismo/
